--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/pradiph31/Downloads/Images/143747.jpg"

-- Special
background="#010709"
foreground="#aacdd9"
cursor="#aacdd9"

-- Colors
color0="#010709"
color1="#27556A"
color2="#455C56"
color3="#C4A64F"
color4="#366D8B"
color5="#447891"
color6="#4F8BA9"
color7="#aacdd9"
color8="#768f97"
color9="#27556A"
color10="#455C56"
color11="#C4A64F"
color12="#366D8B"
color13="#447891"
color14="#4F8BA9"
color15="#aacdd9"
