# Shell variables
# Generated by 'wal'
wallpaper='/home/pradiph31/Downloads/Images/143747.jpg'

# Special
background='#010709'
foreground='#aacdd9'
cursor='#aacdd9'

# Colors
color0='#010709'
color1='#27556A'
color2='#455C56'
color3='#C4A64F'
color4='#366D8B'
color5='#447891'
color6='#4F8BA9'
color7='#aacdd9'
color8='#768f97'
color9='#27556A'
color10='#455C56'
color11='#C4A64F'
color12='#366D8B'
color13='#447891'
color14='#4F8BA9'
color15='#aacdd9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
